### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by GityupGit** [jaredsohn/okcnotes#2]
Thanks for your work on this script. Currently it is not working for me either as a userscript or as a Chrome app. Using newest Mac operating system and newest version of Chrome. I think it used to work for me. Have you heard of any problems with the script or possibly conflict with other scripts or apps?

**Comment by jaredsohn** [comment]
Unfortunately, I am pretty sure this script is dead.

When this script was built, you could still see/edit existing notes and this script just allowed you to add notes where there were none.  After some time, OkCupid took away existing notes and broke this script.

Not sure what the best solution is at the moment. I tried out a Chrome extension that lets you add sticky notes on top of any website, but I haven't gotten into the habit of using it yet.
